<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
                <div class="alert alert-block alert-warning">
                    <h4>
                        Recupere sua senha
                    </h4>
                    Informe seu nome de usuario e verifique sua caixa de email.
                </div>
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">E-mail:</label>
                        <div class="col-sm-8">
                            <input type="email" name="email" class="form-control" id="email" placeholder="email@site.com.br">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                            <button type="submit" class="btn btn-success">Recuperar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
