-- MySQL Script generated by MySQL Workbench
-- 08/19/16 14:18:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema impulse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema impulse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `impulse` DEFAULT CHARACTER SET utf8 ;
USE `impulse` ;

-- -----------------------------------------------------
-- Table `impulse`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impulse`.`roles` (
  `id` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impulse`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impulse`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `user_password` CHAR(128) NOT NULL,
  `salt` CHAR(128) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 1,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk1_user_role_id_idx` (`role_id` ASC),
  CONSTRAINT `fk1_user_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `impulse`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impulse`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impulse`.`login_attempts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk1_login_attempt_user_idx` (`user_id` ASC),
  CONSTRAINT `fk1_login_attempt_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `impulse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impulse`.`recoveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impulse`.`recoveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk1_password_user_idx` (`user_id` ASC),
  CONSTRAINT `fk1_password_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `impulse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
